version: "3.9"
services:
  backend:
    build: ./backend
    container_name: tracker-backend
    restart: always
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: tracker-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
